#!/usr/bin/env python3
"""
Test MetaGPT Deep Research integration
测试MetaGPT DR生成文章功能
"""

import asyncio
import json
from pathlib import Path
from datetime import datetime

# Test without MetaGPT import first to see if config works
def test_config():
    """测试配置文件是否正确"""
    config_path = Path.home() / ".metagpt" / "config2.yaml"
    if config_path.exists():
        print(f"✓ Config file exists: {config_path}")
        return True
    else:
        print(f"✗ Config file not found: {config_path}")
        return False

def test_simple_dr():
    """测试简单的DR调用（先用模拟）"""
    print("\nTesting DR article generation (simulated)...")

    # 模拟trending topic
    trending_topic = {
        'title': 'OpenAI Releases New GPT Model with Reasoning Capabilities',
        'source': 'hackernews',
        'engagement_score': 500,
        'url': 'https://news.ycombinator.com/item?id=123456'
    }

    print(f"Topic: {trending_topic['title']}")
    print(f"Source: {trending_topic['source']}")
    print(f"Score: {trending_topic['engagement_score']}")

    # 模拟DR生成的文章内容
    mock_article = {
        'title': trending_topic['title'],
        'content': """# OpenAI Releases New GPT Model with Reasoning Capabilities

## Executive Summary

OpenAI has announced the release of a new GPT model that demonstrates enhanced reasoning capabilities, marking a significant advancement in artificial intelligence technology.

## Key Features

The new model introduces several groundbreaking capabilities:

1. **Enhanced Logical Reasoning**: The model can perform multi-step logical deductions
2. **Improved Mathematical Problem Solving**: Better handling of complex mathematical concepts
3. **Code Generation Improvements**: More accurate and efficient code generation

## Technical Details

The model utilizes a novel architecture that combines traditional transformer mechanisms with new reasoning modules...

## Industry Impact

This development is expected to have significant implications for:
- Software development automation
- Scientific research acceleration
- Educational technology advancement

## Conclusion

The release of this new model represents a major step forward in AI capabilities, bringing us closer to artificial general intelligence.

---
*Generated by TrendForge Deep Research*
""",
        'word_count': 150,
        'generation_time': 45.2
    }

    # 保存到文件（模拟）
    output_dir = Path("/mnt/d/gitlab_deepwisdom/trendforge/content/blog")
    output_dir.mkdir(parents=True, exist_ok=True)

    # 生成文件名
    date_str = datetime.now().strftime("%Y%m%d")
    filename = f"{date_str}_openai_gpt_reasoning.md"
    filepath = output_dir / filename

    # 生成frontmatter
    frontmatter = f"""---
title: "{mock_article['title']}"
date: {datetime.now().isoformat()}
source: {trending_topic['source']}
engagement_score: {trending_topic['engagement_score']}
word_count: {mock_article['word_count']}
generation_time: {mock_article['generation_time']}
---

"""

    # 写入文件
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(frontmatter)
        f.write(mock_article['content'])

    print(f"\n✓ Article saved to: {filepath}")
    print(f"✓ Word count: {mock_article['word_count']}")
    print(f"✓ Generation time: {mock_article['generation_time']}s")

    return True

async def test_real_dr():
    """测试真实的DR调用（需要安装MetaGPT）"""
    try:
        from metagpt.roles.researcher import Researcher
        from metagpt.logs import logger

        print("\n✓ MetaGPT imported successfully!")

        # 创建DR实例
        researcher = Researcher()

        # 测试话题
        topic = "Latest developments in AI reasoning models and their impact on software development"

        print(f"\nGenerating article for: {topic}")
        print("This may take 30-60 seconds...")

        # 生成文章
        result = await researcher.run(topic)

        print(f"\n✓ Article generated!")
        print(f"Length: {len(result)} characters")

        # 保存文章
        output_dir = Path("/mnt/d/gitlab_deepwisdom/trendforge/content/blog")
        output_dir.mkdir(parents=True, exist_ok=True)

        date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{date_str}_ai_reasoning_dr.md"
        filepath = output_dir / filename

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(result)

        print(f"✓ Saved to: {filepath}")

        return True

    except ImportError as e:
        print(f"\n⚠ MetaGPT not installed: {e}")
        print("\nTo install MetaGPT DR, run:")
        print("pip install git+ssh://git@gitlab.deepwisdomai.com/pub/MetaGPT.git@dr4run")
        return False
    except Exception as e:
        print(f"\n✗ Error running DR: {e}")
        return False

def main():
    print("="*60)
    print("MetaGPT Deep Research Test")
    print("="*60)

    # 测试配置
    config_ok = test_config()

    if not config_ok:
        print("\nPlease ensure config file is in place:")
        print("cp backend/config/metagpt_config.yaml ~/.metagpt/config2.yaml")
        return

    # 测试模拟DR（不需要安装）
    test_simple_dr()

    # 尝试真实DR（需要安装）
    print("\n" + "="*60)
    print("Attempting real DR test...")
    print("="*60)

    try:
        asyncio.run(test_real_dr())
    except Exception as e:
        print(f"Could not run async DR test: {e}")

    print("\n" + "="*60)
    print("Test Summary")
    print("="*60)
    print("✓ Config file in place")
    print("✓ Mock DR generation works")
    print("? Real DR requires MetaGPT installation")

    print("\nNext steps:")
    print("1. Install MetaGPT DR: pip install git+ssh://git@gitlab.deepwisdomai.com/pub/MetaGPT.git@dr4run")
    print("2. Get Tavily API key from tavily.com for search functionality")
    print("3. Run full pipeline test: python backend/pipeline.py")

if __name__ == "__main__":
    main()